name: LoraApp
description: A new Flutter project for Lora.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2      # Check for the latest version on pub.dev
  english_words: ^4.0.0
  provider: ^6.0.0
  latlong2: ^0.9.1
  geolocator: ^9.0.2
  firebase_core: ^3.7.0
  firebase_database: ^11.1.5
  cloud_firestore: ^5.4.5
  supabase_flutter: ^2.8.3
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
  - assets/images/cat.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/cat.png" 